using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ScoreboardModel 
{
    [RealtimeProperty(1, true, true)] private string _scoreBoardText;
    [RealtimeProperty(2, true, false)] private RealtimeDictionary<PlayerDataModel> _players;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ScoreboardModel : RealtimeModel {
    public string scoreBoardText {
        get {
            return _scoreBoardTextProperty.value;
        }
        set {
            if (_scoreBoardTextProperty.value == value) return;
            _scoreBoardTextProperty.value = value;
            InvalidateReliableLength();
            FireScoreBoardTextDidChange(value);
        }
    }
    
    public Normal.Realtime.Serialization.RealtimeDictionary<PlayerDataModel> players {
        get => _players;
    }
    
    public delegate void PropertyChangedHandler<in T>(ScoreboardModel model, T value);
    public event PropertyChangedHandler<string> scoreBoardTextDidChange;
    
    public enum PropertyID : uint {
        ScoreBoardText = 1,
        Players = 2,
    }
    
    #region Properties
    
    private ReliableProperty<string> _scoreBoardTextProperty;
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<PlayerDataModel>> _playersProperty;
    
    #endregion
    
    public ScoreboardModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _players = new Normal.Realtime.Serialization.RealtimeDictionary<PlayerDataModel>();
        childModels[0] = _players;
        
        SetChildren(childModels);
        
        _scoreBoardTextProperty = new ReliableProperty<string>(1, _scoreBoardText);
        _playersProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<PlayerDataModel>>(2, _players);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _scoreBoardTextProperty.UnsubscribeCallback();
    }
    
    private void FireScoreBoardTextDidChange(string value) {
        try {
            scoreBoardTextDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _scoreBoardTextProperty.WriteLength(context);
        length += _playersProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _scoreBoardTextProperty.Write(stream, context);
        writes |= _playersProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ScoreBoardText: {
                    changed = _scoreBoardTextProperty.Read(stream, context);
                    if (changed) FireScoreBoardTextDidChange(scoreBoardText);
                    break;
                }
                case (uint) PropertyID.Players: {
                    changed = _playersProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _scoreBoardText = scoreBoardText;
        _players = players;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
